"""
Django settings for minilang_project project.

Generated by 'django-admin startproject' using Django 4.2.15.
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# ===============================
# CONFIGURACIÓN GENERAL
# ===============================
SECRET_KEY = 'django-insecure-e62osqk9es)chi_xhndo_pdkj*1y1+b0=)+=y0d_&wwn)7d2@!'
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# ===============================
# APLICACIONES INSTALADAS
# ===============================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'interpreter',  # tu app
]

# ===============================
# MIDDLEWARE
# ===============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ⚡ necesario para Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'minilang_project.urls'

# ===============================
# TEMPLATES
# ===============================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'interpreter' / 'templates'],  # 📁 tu carpeta de templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'minilang_project.wsgi.application'

# ===============================
# BASE DE DATOS
# ===============================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ===============================
# VALIDADORES DE CONTRASEÑA
# ===============================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ===============================
# INTERNACIONALIZACIÓN
# ===============================
LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Mexico_City'
USE_I18N = True
USE_TZ = True

# ===============================
# ARCHIVOS ESTÁTICOS (CSS, JS, IMG)
# ===============================
STATIC_URL = '/static/'

# 👉 Aquí le decimos a Django dónde están tus archivos CSS (dentro de tu app)
STATICFILES_DIRS = [
    BASE_DIR / 'interpreter' / 'static',  # Ajustado al nombre de tu app
]

# 👉 Carpeta donde se reunirán todos los archivos estáticos al hacer deploy
STATIC_ROOT = BASE_DIR / 'staticfiles'

# --- Configuración especial para Render ---
if 'RENDER' in os.environ:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ===============================
# CONFIGURACIÓN FINAL
# ===============================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
